Get component page (#264)
* Update multilingual.service.ts (#235)

* Fix for #292, NPM run clean fails with TSError: ⨯ Unable to compile TypeScript (#233)

* Fix #232 - npm run clean fails with compilation error

* Version 2.0.0 of @angular/platform-server

* feat: Getting the Components Page-object in {N}

* fix: remove PageComponent Decorator and use Injector to get Page-object instead

* undo: changes in DecoratorUtils no longer needed -> undoing